// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FsGrakn")>]
[<assembly: AssemblyVersionAttribute("0.0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1.0")>]
[<assembly: AssemblyDescriptionAttribute(".NET driver for Grakn.AI knowledge graph")>]
[<assembly: InternalsVisibleToAttribute("FsGrakn.Test")>]
[<assembly: AssemblyProductAttribute("FsGrakn")>]
[<assembly: GuidAttribute("5341159e-5f87-40aa-a5e1-0d7dea3d4fe3")>]
[<assembly: AssemblyCopyrightAttribute("Gregor Beyerle - gregor.beyerle@gmail.com")>]
[<assembly: AssemblyMetadataAttribute("githash","c177f6")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsGrakn"
    let [<Literal>] AssemblyVersion = "0.0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.0.1.0"
    let [<Literal>] AssemblyDescription = ".NET driver for Grakn.AI knowledge graph"
    let [<Literal>] InternalsVisibleTo = "FsGrakn.Test"
    let [<Literal>] AssemblyProduct = "FsGrakn"
    let [<Literal>] Guid = "5341159e-5f87-40aa-a5e1-0d7dea3d4fe3"
    let [<Literal>] AssemblyCopyright = "Gregor Beyerle - gregor.beyerle@gmail.com"
    let [<Literal>] AssemblyMetadata_githash = "c177f6"
